services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN_USER: $HIVE_KEYCLOAK_ADMIN_USER
      KEYCLOAK_ADMIN_PASSWORD: $HIVE_KEYCLOAK_ADMIN_PASSWORD
      KEYCLOAK_DATABASE_VENDOR: dev-file
    ports:
      - "8080:8080"
    volumes:
      - keycloak:/bitnami/keycloak

  terraform-init:
    build:
      context: ./terraform
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ADMIN_USER: $HIVE_KEYCLOAK_ADMIN_USER
      KEYCLOAK_ADMIN_PASSWORD: $HIVE_KEYCLOAK_ADMIN_PASSWORD
      KEYCLOAK_URL: "http://keycloak:8080"
    depends_on:
      - keycloak

volumes:
  keycloak:
